name: microlab

networks:
  microlab:
    driver: bridge

services:

  lab-01:
    build: ./labs/lab-01
    ports:
      - "8001:8000"
    volumes:
      - ./labs/lab-01/src:/app/src
    environment:
      - PAYMENT_FAILURE_RATE=0.0
    networks:
      - microlab
    profiles: [lab-01]
    restart: unless-stopped

  lab-02:
    build: ./labs/lab-02
    ports:
      - "8002:8000"
    volumes:
      - ./labs/lab-02/src:/app/src
    networks:
      - microlab
    profiles: [lab-02]
    restart: unless-stopped
