name: microlab

networks:
  microlab:
    driver: bridge

services:

  # ─── NGINX ─────────────────────────────────────────────────────────────────
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./platform/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ui
      - orchestrator
    networks:
      - microlab
    restart: unless-stopped

  # ─── UI ────────────────────────────────────────────────────────────────────
  ui:
    build: ./platform/ui
    networks:
      - microlab
    restart: unless-stopped

  # ─── ORQUESTRADOR ──────────────────────────────────────────────────────────
  orchestrator:
    build: ./platform/orchestrator
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/app/.env
      - ./labs:/app/labs
    environment:
      - LABS_PATH=/app/labs
    networks:
      - microlab
    restart: unless-stopped

  # ─── LAB 01 ────────────────────────────────────────────────────────────────
  lab-01:
    build: ./labs/lab-01
    ports:
      - "8001:8000"
    volumes:
      - ./labs/lab-01/src:/app/src
    environment:
      - PAYMENT_FAILURE_RATE=0.0
    networks:
      - microlab
    profiles: [lab-01]
    restart: unless-stopped

  # ─── LAB 02 ────────────────────────────────────────────────────────────────
  lab-02:
    build: ./labs/lab-02
    ports:
      - "8002:8000"
    volumes:
      - ./labs/lab-02/src:/app/src
    networks:
      - microlab
    profiles: [lab-02]
    restart: unless-stopped