global:
  scrape_interval: 5s

scrape_configs:
  - job_name: lab-01
    static_configs:
      - targets: [lab-01:8000]

  - job_name: lab-03-orders
    static_configs:
      - targets: [lab-03-orders:8000]

  - job_name: lab-03-payments
    static_configs:
      - targets: [lab-03-payments:8000]

  - job_name: lab-05
    static_configs:
      - targets: [lab-05:8000]
