events {}

http {
  include      mime.types;
  default_type application/octet-stream;

  server {
    listen 80;

    location / {
      proxy_pass http://ui:3000;
    }

    location /api/ {
      proxy_pass         http://orchestrator:4000/api/;
      proxy_buffering    off;
      proxy_cache        off;
      proxy_read_timeout 3600s;
      proxy_set_header   Connection '';
      chunked_transfer_encoding on;
    }

    location /health {
      return 200 "ok\n";
      add_header Content-Type text/plain;
    }
  }
}